### ISSUE TITLE
Package fails to install

### ISSUE THREAD

**Issue by vanagonjon** [optimistiCli/uidmaker#1]
I've created the .spk file per the readme instructions, but upon installation of the package I get the following error:

this package is not supported on the platform of diskstation or is incompatible with the current DSM version

I'm installing this on a DS218+ with a Celeron J3355 on DSM version 6.2.2-24922 Update 3. I know nothing about developing on diskstation, I poked around the template files, but nothing jumps out at me. Any thoughts? Thank you for this contribution!

**Comment by optimistiCli** [comment]
It doesn't reproduce here. Worked as intended on 6.2 and 6.2.2 testbeds. I don't have a DS218+ though. Are you sure it is a x86_64 system?
